---
title: "Day 2"
output: html_document
---

## *Day 2* of My Organization's First R Package 

Making an R package for your organization can either be a short process or a long process. Most of the time it'll be a long, yet enjoyable, process. One hopes that data users in the organization will see the value of the package and thus more potential uses (and additions).

We can only cover so much in a day of workshoppin'. Day 1 teaches us all about how to generate a package that has all the necessary components in place. If we keep following all of the tasks of adding functions, documenting, testing, etc., then we'll have a healthy and usable package. Now, we just ideas for useful functions that suit the modern organization.

Everybody's needs are different though! What kind of organization are you in? What kind will you be in, in the future? What tools will the organization use? Files available on a file system or a database? What does the data department value? Is the data department just you? Really, every situation is different.

We can only do **4** modules today out of the **5** available. That's okay, the course materials will be available on the website and you could always reach out to us to discuss the contents of the 'bonus' module.

Today, we'll learn about:

 1. `databases` and easier access to them through an organizational R package
 2. Designing `pkg_functions` for reporting KPIs and getting data segments
 3. `pkg_management`: the management and communication around an internal R package
 4. Designing `standardized_reporting` functions to standardize tables and plots for reporting needs
 
The extra module is:

 5. `pkg_quality`: ensuring we have a handle on package quality
 
## Periods Where YOU CODE Using Simulated Data

There are time allotments for coding up a function (or *several*) that would be useful in a package that's only meant to be used with a specific organization's data. We have a publicly-hostly database at our disposal with data tables that we'll use for all the examples and for the YOU CODE exercises. The tables are a bit domain-specific and we do have to spend a little bit of time understanding the lingo and the business logic that goes with it. After that, things should be easier to understand.

We are providing possible solutions to the YOU CODE exercises (the file is called `z_possible_answers.R`). Feel free to look at it to get unstuck. There will also be a number of TAs available to guide you through and provide some ideas. Don't ever worry about the 'correctness' or 'completeness' of any of your work. Functions like we are trying to expose you to take a lot of time to fully work out. The main purpose of the workshop exercises is more-or-less to expose you to some design ideas (which may be flawed!) that you could adapt in your own organization's R package. You could work alone or work in a small group... do whatever suits your style of work and feel to experiment with ideas of your own. You won't be graded!

## About that Simulated Data

All of the code to generate it is available in the `generate_game_studio_data.R` script. Yes, it does try to simulate analytics data you might find at a game studio. It's by no means a very reasonable simulation of user behavior in the game space but it should serve us well at least for the purposes of this workshop.

The dataset generation script takes a very long time to run. If you'd prefer to skip all of that processing time, RDS files for the three tables are available in the repo as `daily_users.rds`, `revenue.rds`, and `users.rds`.
