---
title: "03_00_pkg_management"
output: html_document
---

## Managing the Development of the Internal Package

Outline of Module

- Finding out what's needed to make the package a success
- Getting people involved and giving their roles
- Initial planning and prioritizing
- Winning support from stakeholders
- Hosting the package in the organization
- The README as the selling point of your package
- A **pkgdown** site is still insanely useful in an organization
- Internal documentation should be seriously buffed
- Super simple examples as documentation: `tldr`
- The data dictionary: so useful, yet, we don't see it often enough
- Training & education requirements for the package
- Quality measures and quality control
- Tracking Issues
- Managing updates and major changes to the package API
- Getting internal users and encouraging contributions
- The package should have a license... which one?
- Communicating the value of the package
- DISCUSSION (20 minutes)
    - Did you do any of these things IRL?
    - What worked and what didn't?
    - Have you ever met any resistance to this sort of enterprise?
    - Do you have any advice from personal experience?
    - Want to share some miscellaneous tips/tricks w.r.t. package dev/mgmt?
