---
title: "Modules for Day 2"
output: html_document
---

## Modules as Chunks of Learning

Making an R package for your organization can either be a short process or a long process. Most of the time it'll be a long, yet enjoyable, process. One hopes that data users in the organization will see the value of the package and thus more potential uses (and additions).

We can only cover so much in a day. Day 1 gave us all the tools to generate a package that has all the necessary components in place. If we keep following all of the tasks of adding functions, documenting, testing, etc., then we'll have a healthy and usable framework. Now, we just ideas for useful functions.

Everybody's needs are different though! What kind of organization are you in? What kind will you be in, in the future? What tools will the organization use? Files available on a file system or a database? What does the data department value? Is the data department just you? Really, every situation is different.

We can only do **4** modules today out of the **7** available. That's okay, the course materials will be available on the website and you could always reach out to us to discuss the contents of the 'bonus' modules.

Today, we'll learn about:

 1. `databases` and easier access to them through an organizational R package
 2. Designing `pkg_functions` for reporting KPIs and getting data segments
 3. `pkg_management`: the management and communication around an internal R package
 4. Designing `standardized_reporting` functions to standardize tables and plots for reporting needs
 
The extra modules are:

 5. Using package `documentation`
 6. `pkg_quality`: ensuring we have a handle on package quality
 7. Developing functions to help assess `data_quality`
