---
title: "05_00_standardized_reporting"
output: html_document
---

## Building Package Functions for Standardizing Reporting

Outline of Module

- Standardization is actually advantageous in organizations
- When and where to use standardized plots and tables
- New package functions (that use our previous functions) to create standardized plots and tables
- CODE DEMO: `04_01_standardized_reporting.Rmd`
    - time-series plots of different revenue types segmented by country
    - YOU CODE (30 minutes)
        - Create a function that generates a **ggplot** with the following:
          - revenue going back 30, 60, or 90 days
          - text annotations of total revenue for every standard week
          - average revenue lines for the above
          - a title and a subtitle that automatically displays the right info about the plot
- CODE DEMO: `04_02_standardized_reporting.Rmd`
    - summary table with different KPIs and revenue data segmented by country
    - YOU CODE (30 minutes)
        - Create a function that generates a **gt** table with the following:
          - weekly average KPI values for DAU, MAU, DAC, ARPU going back 60 days
          - total revenue (IAP revenue + advertising revenue)
          - include averages over the entire period and grand total sum of revenue
          - a title and subtitle that automatically displays the information about the table
